### GET Clientes
GET http://localhost:8080/api/v1/clientes
Content-Type: application/json

### POST Clientes
POST http://localhost:8080/api/v1/clientes
Content-Type: application/json

{"id":0,
"nome":" ",
"email":"giovana.mendes@hotmail.com",
"telefone":"47 8888-8888",
"cpf":"222.222.222-22"
}

### PUT Clientes
PUT http://localhost:8080/api/v1/clientes/1
Content-Type: application/json

{"id":0,
"nome":" ",
"email":"giovana.mend",
"telefone":"47 8888-8888",
"cpf":"222.222.222-22"
}