### GET Clientes
GET http://localhost:8080/api/v1/clientes
Content-Type: application/json

### POST Clientes
POST http://localhost:8080/api/v1/clientes
Content-Type: application/json

{"id":0,
"nome":"Giovana",
"email":"giovana.mendes@hotmail.com",
"telefone":"47 8888-8888",
"cpf":"222.222.222-22"
}

### PUT Clientes
PUT http://localhost:8080/api/v1/clientes/1
Content-Type: application/json

{"id":0,
"nome":"José",
"email":"giovana.balal",
"telefone":"47 8888-8888",
"cpf":"222.222.222-22"
}

### DELETE Clientes
DELETE http://localhost:8080/api/v1/clientes/3
Content-Type: application/json

##--------------- // ----------------- // ------------------

### GET Reservas
GET http://localhost:8080/api/v1/reservas
Content-Type: application/json

### POST Reservas
POST http://localhost:8080/api/v1/reservas
Content-Type: application/json

{"id":0,
"dataHoraInicio":"2024-06-20",
"dataHoraFim":"2024-06-20",
"valorTotal":"202.00",
"cliente": { "id": 1 },
"quadra": { "id": 1 },
"status":1}

### PUT Reservas
PUT http://localhost:8080/api/v1/reservas/6
Content-Type: application/json

{"id":0,
"dataHoraInicio":"2024-06-20",
"dataHoraFim":"2024-06-20",
"valorTotal":"101.00",
"cliente": { "id": 4 },
"quadra": { "id": 1 },
"status":0}

### DELETE Reservas
DELETE http://localhost:8080/api/v1/reservas/2
Content-Type: application/json